include $(APPDIR)/Make.defs

APP_NAME = semphore
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048

MAINSRC = semaphore_ex.c

CONFIG_MY_APP_PROGNAME ?= semaphore$(EXEEXT)
PROGNAME = $(CONFIG_MY_APP_PROGNAME)

include $(APPDIR)/Application.mk
